version: "3"

services:
  flarum:
    image: flarum
    container_name: flarum
    ports:
      - 9999:8888
    build:
      context: ./flarum
      dockerfile: Dockerfile
    volumes:
      - /data/site/flarum/site/public/assets:/flarum/app/public/assets
    #  - /data/site/flarum/site/extensions:/flarum/app/extensions
    #  - /data/site/flarum/site/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=4321bcvda
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=abcd1234
    volumes:
      - /data/site/flarum/db:/var/lib/mysql