version: "3"

services:
  flarum:
    image: flarum
    container_name: flarum
    
    #volumes:
    #  - /mnt/docker/flarum/assets:/flarum/app/public/assets
    #  - /mnt/docker/flarum/extensions:/flarum/app/extensions
    #  - /mnt/docker/flarum/nginx:/etc/nginx/conf.d
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=4321bcvda
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=abcd1234
    volumes:
      - /mnt/docker/mysql/db:/var/lib/mysql